---
name: Check
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:

jobs:
  security:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      # PHP checks
      - name: Check for php composer project
        id: check_composer
        uses: andstor/file-existence-action@v2
        with:
          files: "composer.lock"
      - name: Run php local security checker
        if: steps.check_composer.outputs.files_exists == 'true'
        uses: symfonycorp/security-checker-action@v4

      # node checks
      - name: Check for node project
        id: check_node
        uses: andstor/file-existence-action@v2
        with:
          files: "yarn.lock"
      - name: Setup node
        if: steps.check_node.outputs.files_exists == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Yarn Audit
        if: steps.check_node.outputs.files_exists == 'true'
        run: yarn audit --level high --groups dependencies optionalDependencies

      # python checks
      - name: Check for python project
        id: check_python
        uses: andstor/file-existence-action@v2
        with:
          files: "requirements.txt"
      - name: Safety checks Python dependencies
        if: steps.check_python.outputs.files_exists == 'true'
        uses: pyupio/safety@2.3.5

      # java checks
      - name: Check for java maven project
        id: check_maven
        uses: andstor/file-existence-action@v2
        with:
          files: "pom.xml"
      - name: Setup java if needed
        if: steps.check_maven.outputs.files_exists == 'true'
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Chack java
        if: steps.check_maven.outputs.files_exists == 'true'
        run: mvn org.owasp:dependency-check-maven:check
